apiRules:
- exclude:
    uidRegex: ^System\.Object
    type: Type
- exclude:
    uidRegex: ^UnityEngine\.Object\..*(Find|Instantiate|Destroy|Equals)
    type: Member
- exclude:
    uidRegex: ^UnityEngine\.Component\..*(Message|Component)
    type: Member
- exclude:
    uidRegex: ^UnityEngine\.MonoBehaviour\..*(Coroutine|Invok|print|destroyCancellationToken|useGUILayout|runInEditMode)
    type: Member
- exclude:
      uidRegex: ^(Packages\.Rider\.Editor\.UnitTesting|JetBrains\.Rider\.Unity\.Editor)
      type: Namespace