# Required secrets
#   UNITY_LICENSE: The contents of Unity license file
name: 🎮 Build Demo Player

env:
  targetPlatform: WebGL

on:
  workflow_call:
    secrets:
      UNITY_LICENSE:
        description: The contents of Unity license file
        required: true
  workflow_dispatch:

jobs:
  build:
    name: 🎮 Build Demo Player
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: ⚙️ Setup Unity version
        id: setup
        run: |
          TARGET_VERSION=`npx unity-changeset list --versions --latest-patch --lts | head -n 1`
          echo "unityVersion=${TARGET_VERSION}" >> $GITHUB_OUTPUT
          echo "Target Unity Version: ${TARGET_VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "Target Unity Version: ${TARGET_VERSION}"

      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 📥 Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ steps.setup.outputs.unityVersion }}-${{ env.targetPlatform }}-${{ github.sha }}
          restore-keys: |
            Library-${{ steps.setup.outputs.unityVersion }}-${{ env.targetPlatform }}-
            Library-${{ steps.setup.outputs.unityVersion }}-
            Library-

      - name: 🛠️ Build Demo Player
        uses: game-ci/unity-builder@v3
        timeout-minutes: 30
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          customImage: mobsakai/unity3d:${{ steps.setup.outputs.unityVersion }}-webgl
          # unityVersion: ${{ steps.setup.outputs.unityVersion }}
          targetPlatform: WebGL
          allowDirtyBuild: true

      - name: 📦 Upload Demo Player
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/WebGL/WebGL